"""Add retirement_villages_core_data table

Revision ID: 396ca3dcc4f1
Revises: 
Create Date: 2025-12-04 16:56:45.268521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '396ca3dcc4f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retirement_villages_core_data',
    sa.Column('ENTITY_NUMBER', sa.String(length=50), nullable=False),
    sa.Column('ENTITY_NAME', sa.String(length=255), nullable=True),
    sa.Column('REGISTRATION_DATE', sa.Date(), nullable=True),
    sa.Column('ENTITY_STATUS', sa.String(length=50), nullable=True),
    sa.Column('PHYSICAL_ADDRESS_1', sa.String(length=255), nullable=True),
    sa.Column('PHYSICAL_ADDRESS_2', sa.String(length=255), nullable=True),
    sa.Column('PHYSICAL_ADDRESS_3', sa.String(length=255), nullable=True),
    sa.Column('PHYSICAL_ADDRESS_4', sa.String(length=255), nullable=True),
    sa.Column('PHYSICAL_POST_CODE', sa.String(length=20), nullable=True),
    sa.Column('OPERATOR_NAME', sa.String(length=255), nullable=True),
    sa.Column('OPERATOR_ADDRESS_1', sa.String(length=255), nullable=True),
    sa.Column('OPERATOR_ADDRESS_2', sa.String(length=255), nullable=True),
    sa.Column('OPERATOR_ADDRESS_3', sa.String(length=255), nullable=True),
    sa.Column('OPERATOR_ADDRESS_4', sa.String(length=255), nullable=True),
    sa.Column('OPERATOR_POST_CODE', sa.String(length=20), nullable=True),
    sa.Column('OPERATOR_DATE_APPOINTED', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('ENTITY_NUMBER')
    )
    op.create_index(op.f('ix_retirement_villages_core_data_ENTITY_NAME'), 'retirement_villages_core_data', ['ENTITY_NAME'], unique=False)
    op.create_index(op.f('ix_retirement_villages_core_data_ENTITY_NUMBER'), 'retirement_villages_core_data', ['ENTITY_NUMBER'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retirement_villages_core_data_ENTITY_NUMBER'), table_name='retirement_villages_core_data')
    op.drop_index(op.f('ix_retirement_villages_core_data_ENTITY_NAME'), table_name='retirement_villages_core_data')
    op.drop_table('retirement_villages_core_data')
    # ### end Alembic commands ###
