"""Add missing columns to retirement_villages_core_data

Revision ID: 8da5065f6d1a
Revises: 396ca3dcc4f1
Create Date: 2025-12-04 17:00:58.166338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8da5065f6d1a'
down_revision: Union[str, None] = '396ca3dcc4f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retirement_villages_core_data', sa.Column('ADDRESS_FOR_PREMISES_1', sa.String(length=255), nullable=True))
    op.add_column('retirement_villages_core_data', sa.Column('ADDRESS_FOR_PREMISES_2', sa.String(length=255), nullable=True))
    op.add_column('retirement_villages_core_data', sa.Column('ADDRESS_FOR_PREMISES_3', sa.String(length=255), nullable=True))
    op.add_column('retirement_villages_core_data', sa.Column('ADDRESS_FOR_PREMISES_4', sa.String(length=255), nullable=True))
    op.add_column('retirement_villages_core_data', sa.Column('ADDRESS_FOR_COMMUNICATION_1', sa.String(length=255), nullable=True))
    op.add_column('retirement_villages_core_data', sa.Column('ADDRESS_FOR_COMMUNICATION_2', sa.String(length=255), nullable=True))
    op.add_column('retirement_villages_core_data', sa.Column('ADDRESS_FOR_COMMUNICATION_3', sa.String(length=255), nullable=True))
    op.add_column('retirement_villages_core_data', sa.Column('ADDRESS_FOR_COMMUNICATION_4', sa.String(length=255), nullable=True))
    op.add_column('retirement_villages_core_data', sa.Column('REGISTERED_OFFICE_ADDRESS_1', sa.String(length=255), nullable=True))
    op.add_column('retirement_villages_core_data', sa.Column('REGISTERED_OFFICE_ADDRESS_2', sa.String(length=255), nullable=True))
    op.add_column('retirement_villages_core_data', sa.Column('REGISTERED_OFFICE_ADDRESS_3', sa.String(length=255), nullable=True))
    op.add_column('retirement_villages_core_data', sa.Column('REGISTERED_OFFICE_ADDRESS_4', sa.String(length=255), nullable=True))
    op.add_column('retirement_villages_core_data', sa.Column('OPERATOR_NUMBER', sa.String(length=50), nullable=True))
    op.add_column('retirement_villages_core_data', sa.Column('STATUTORY_SUPERVISOR_NAME', sa.String(length=255), nullable=True))
    op.add_column('retirement_villages_core_data', sa.Column('STATUTORY_SUPERVISOR_ADDRESS_1', sa.String(length=255), nullable=True))
    op.add_column('retirement_villages_core_data', sa.Column('STATUTORY_SUPERVISOR_ADDRESS_2', sa.String(length=255), nullable=True))
    op.add_column('retirement_villages_core_data', sa.Column('STATUTORY_SUPERVISOR_ADDRESS_3', sa.String(length=255), nullable=True))
    op.add_column('retirement_villages_core_data', sa.Column('STATUTORY_SUPERVISOR_ADDRESS_4', sa.String(length=255), nullable=True))
    op.add_column('retirement_villages_core_data', sa.Column('STATUTORY_SUPERVISOR_DATE_APPOINTED', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('retirement_villages_core_data', 'STATUTORY_SUPERVISOR_DATE_APPOINTED')
    op.drop_column('retirement_villages_core_data', 'STATUTORY_SUPERVISOR_ADDRESS_4')
    op.drop_column('retirement_villages_core_data', 'STATUTORY_SUPERVISOR_ADDRESS_3')
    op.drop_column('retirement_villages_core_data', 'STATUTORY_SUPERVISOR_ADDRESS_2')
    op.drop_column('retirement_villages_core_data', 'STATUTORY_SUPERVISOR_ADDRESS_1')
    op.drop_column('retirement_villages_core_data', 'STATUTORY_SUPERVISOR_NAME')
    op.drop_column('retirement_villages_core_data', 'OPERATOR_NUMBER')
    op.drop_column('retirement_villages_core_data', 'REGISTERED_OFFICE_ADDRESS_4')
    op.drop_column('retirement_villages_core_data', 'REGISTERED_OFFICE_ADDRESS_3')
    op.drop_column('retirement_villages_core_data', 'REGISTERED_OFFICE_ADDRESS_2')
    op.drop_column('retirement_villages_core_data', 'REGISTERED_OFFICE_ADDRESS_1')
    op.drop_column('retirement_villages_core_data', 'ADDRESS_FOR_COMMUNICATION_4')
    op.drop_column('retirement_villages_core_data', 'ADDRESS_FOR_COMMUNICATION_3')
    op.drop_column('retirement_villages_core_data', 'ADDRESS_FOR_COMMUNICATION_2')
    op.drop_column('retirement_villages_core_data', 'ADDRESS_FOR_COMMUNICATION_1')
    op.drop_column('retirement_villages_core_data', 'ADDRESS_FOR_PREMISES_4')
    op.drop_column('retirement_villages_core_data', 'ADDRESS_FOR_PREMISES_3')
    op.drop_column('retirement_villages_core_data', 'ADDRESS_FOR_PREMISES_2')
    op.drop_column('retirement_villages_core_data', 'ADDRESS_FOR_PREMISES_1')
    op.drop_index(op.f('ix_companies_core_data_NZBN'), table_name='companies_core_data')
    op.drop_index(op.f('ix_companies_core_data_ENTITY_NAME'), table_name='companies_core_data')
    op.alter_column('companies_core_data', 'ENTITY_STATUS',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('companies_core_data', 'ENTITY_TYPE',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('companies_core_data', 'COMPANY_IDENTIFIER',
               existing_type=sa.String(length=50),
               type_=mysql.BIGINT(),
               existing_nullable=True)
    op.alter_column('companies_core_data', 'NZBN',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.create_table('companies_trading_name',
    sa.Column('NZBN', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ENTITY_NAME', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('START_DATE', sa.DATE(), nullable=True),
    sa.Column('TRADING_NAME', mysql.VARCHAR(length=255), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('companies_registered_office_address',
    sa.Column('NZBN', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ENTITY_NAME', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('START_DATE', sa.DATE(), nullable=True),
    sa.Column('REGISTERED_OFFICE_ADDRESS_PAF_ID', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('REGISTERED_OFFICE_ADDRESS_CARE_OF', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('REGISTERED_OFFICE_ADDRESS_ADDRESS_1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('REGISTERED_OFFICE_ADDRESS_ADDRESS_2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('REGISTERED_OFFICE_ADDRESS_ADDRESS_3', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('REGISTERED_OFFICE_ADDRESS_ADDRESS_4', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('REGISTERED_OFFICE_ADDRESS_POSTCODE', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('REGISTERED_OFFICE_ADDRESS_COUNTRY', mysql.VARCHAR(length=255), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('companies_gst',
    sa.Column('NZBN', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ENTITY_NAME', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('START_DATE', sa.DATE(), nullable=True),
    sa.Column('GST_NUMBER', mysql.BIGINT(), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('unincorporated_entities_core_data',
    sa.Column('NZBN', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ENTITY_NAME', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ENTITY_TYPE', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ENTITY_STATUS', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('REGISTRATION_DATE', sa.DATE(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('other_incorporated_entities_core_data',
    sa.Column('NZBN', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('INCORPORATION_NUMBER', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ENTITY_NAME', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ENTITY_TYPE', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ENTITY_STATUS', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('REGISTRATION_DATE', sa.DATE(), nullable=True),
    sa.Column('DEREGISTRATION_DATE', sa.DATE(), nullable=True),
    sa.Column('INCORPORATED_SOCIETIES_ACT', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('INCSOC2022ACT_REREGISTRATION_DATE', sa.DATE(), nullable=True),
    sa.Column('CHARITIES_REGISTER_NUMBER', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('REGISTERED_OFFICE_ADDRESS_PAF_ID', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('REGISTERED_OFFICE_ADDRESS_CARE_OF', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('REGISTERED_OFFICE_ADDRESS_LINE_1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('REGISTERED_OFFICE_ADDRESS_LINE_2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('REGISTERED_OFFICE_ADDRESS_LINE_3', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('REGISTERED_OFFICE_ADDRESS_LINE_4', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('REGISTERED_OFFICE_ADDRESS_POSTCODE', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('REGISTERED_OFFICE_ADDRESS_COUNTRY', mysql.VARCHAR(length=255), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('companies_public_address',
    sa.Column('NZBN', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ENTITY_NAME', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('TYPE', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('START_DATE', sa.DATE(), nullable=True),
    sa.Column('ADDRESS_PAF_ID', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ADDRESS_CARE_OF', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ADDRESS_1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ADDRESS_2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ADDRESS_3', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ADDRESS_4', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ADDRESS_POSTCODE', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ADDRESS_COUNTRY', mysql.VARCHAR(length=255), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('contact_messages',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('company', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('maori_business_identifier',
    sa.Column('NZBN', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('START_DATE', sa.DATE(), nullable=True),
    sa.Column('IDENTIFYING_FACTOR', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('IDENTIFYING_FACTOR_OTHER_DESC', mysql.BIGINT(), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('companies_trading_area',
    sa.Column('NZBN', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ENTITY_NAME', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('START_DATE', sa.DATE(), nullable=True),
    sa.Column('TRADING_AREA', mysql.VARCHAR(length=255), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('public_sector_entities_core_data',
    sa.Column('NZBN', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ENTITY_NAME', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ENTITY_TYPE', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ENTITY_STATUS', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('REGISTRATION_DATE', sa.DATE(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('companies_insolvency',
    sa.Column('NZBN', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ENTITY_NAME', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('START_DATE', sa.DATE(), nullable=True),
    sa.Column('INSOLVENCY_TYPE', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('APPOINTMENT_TYPE', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('APPOINTEE_FIRST_NAME', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('APPOINTEE_MIDDLE_NAMES', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('APPOINTEE_LAST_NAME', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('APPOINTMENT_DATE', sa.DATE(), nullable=True),
    sa.Column('APPOINTMENT_VACATED_DATE', sa.DATE(), nullable=True),
    sa.Column('ORGANISATION', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('RESSOLUTION_OF_SOLVENCY', mysql.VARCHAR(length=255), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('companies_website',
    sa.Column('NZBN', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ENTITY_NAME', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('START_DATE', sa.DATE(), nullable=True),
    sa.Column('WEBSITE', mysql.VARCHAR(length=255), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('companies_director',
    sa.Column('NZBN', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ENTITY_NAME', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('START_DATE', sa.DATE(), nullable=True),
    sa.Column('FIRST_NAME', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('MIDDLE_NAMES', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('LAST_NAME', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ASIC_DIR_YN', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ACN', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ASIC_COMPANY_NAME', mysql.VARCHAR(length=255), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('companies_address_for_service',
    sa.Column('NZBN', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ENTITY_NAME', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('START_DATE', sa.DATE(), nullable=True),
    sa.Column('ADDRESS_FOR_SERVICE_PAF_ID', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ADDRESS_FOR_SERVICE_CARE_OF', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ADDRESS_FOR_SERVICE_1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ADDRESS_FOR_SERVICE_2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ADDRESS_FOR_SERVICE_3', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ADDRESS_FOR_SERVICE_4', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ADDRESS_FOR_SERVICE_POSTCODE', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ADDRESS_FOR_SERVICE_COUNTRY', mysql.VARCHAR(length=255), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('companies_shareholder',
    sa.Column('NZBN', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ENTITY_NAME', mysql.TEXT(), nullable=True),
    sa.Column('SH_NAME', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('SH_TYPE', mysql.TEXT(), nullable=True),
    sa.Column('START_DATE', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('SH_STATUS', mysql.TEXT(), nullable=True),
    sa.Column('PARCEL_IDENTIFIER', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ASSIGNMENT_IDENTIFIER', mysql.TEXT(), nullable=True),
    sa.Column('NUMBER_OF_SHARES', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('SH_EXTENSIVE_SHAREHOLDING_YN', mysql.TEXT(), nullable=True),
    sa.Column('SH_ADDRESS_PAF_ID', mysql.TEXT(), nullable=True),
    sa.Column('SH_ADDRESS_CARE_OF', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('SH_ADDRESS_1', mysql.TEXT(), nullable=True),
    sa.Column('SH_ADDRESS_2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('SH_ADDRESS_3', mysql.TEXT(), nullable=True),
    sa.Column('SH_ADDRESS_4', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('SH_ADDRESS_POSTCODE', mysql.TEXT(), nullable=True),
    sa.Column('SH_ADDRESS_COUNTRY', mysql.VARCHAR(length=255), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('companies_business_industry_classification',
    sa.Column('NZBN', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ENTITY_NAME', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('START_DATE', sa.DATE(), nullable=True),
    sa.Column('INDUSTRY_CLASSIFICATION_CODE', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('INDUSTRY_CLASSIFICATION_DESCRIPTION', mysql.VARCHAR(length=255), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('companies_abn',
    sa.Column('NZBN', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ENTITY_NAME', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ABN', mysql.BIGINT(), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
